# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. checkout code
      - uses: actions/checkout@v3

      # 2. QEMU + Buildx setup
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      # 3. restore build cache
      - name: Restore buildx cache
        uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-cache

      # 4. build with cache-from/to
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            --load \
            -f Dockerfile \
            -t my-nl2sql-app:ci .

      # 5. save cache if miss
      - name: Save buildx cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-cache

      # 6. run pytest inside container, with PYTHONPATH so imports work
      - name: Run tests in container
        run: |
          docker run --rm \
            -e PYTHONPATH=/app/src:/app \
            my-nl2sql-app:ci \
            pytest --maxfail=1 --disable-warnings -q
