name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Build your Docker image (uses Dockerfile in repo root)
      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag my-nl2sql-app:ci .

      # 3) Run pytest inside the container
      - name: Run tests in container
        run: |
          docker run --rm my-nl2sql-app:ci \
            pytest --maxfail=1 --disable-warnings -q
